/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Vaca;
import modelo.VacaDB;

/**
 *
 * @author PERSONAL
 */
public class FrmDiagPanelPropietario extends javax.swing.JDialog {

    private int contVacasTotal;
    private int contVacasSanas;
    private int contVacasEnfermas;

    public FrmDiagPanelPropietario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        FrmPrincipal.listadoDeVacas.clear(); //Se hace esto para que cada vez que entre no mantenga los datos que tenia antes

        this.contVacasTotal = 0;
        this.contVacasSanas = 0;
        this.contVacasEnfermas = 0;

        this.setLocationRelativeTo(null);
        this.lblNombrePropietario.setText(FrmPrincipal.propietarioPrincipal.getNombres());

        informacionConteoDeVacas();
        cargarInfoEnlbl();

    }

    private void informacionConteoDeVacas() {

        FrmPrincipal.listadoDeVacas.clear(); // Por si hay alguna actualización se vuelven a cargar las vacas
        this.contVacasTotal = 0;
        this.contVacasSanas = 0;
        this.contVacasEnfermas = 0; // Al igual que los contadores

        Vaca objVaca = new Vaca();
        objVaca.setCedula(FrmPrincipal.propietarioPrincipal.getCedula());
        VacaDB objVacaDB = new VacaDB();

        //Se almacenan las vacas de la base de datos en un ArrayList
        for (Object obj : objVacaDB.listarVacasPorPropietario(objVaca)) {
            FrmPrincipal.listadoDeVacas.add((Vaca) obj);
        }

        //Se hace el conteo
        for (int i = 0; i < FrmPrincipal.listadoDeVacas.size(); i++) {

            if (FrmPrincipal.listadoDeVacas.get(i).getEstado().equals("Sana")) {
                this.contVacasSanas++;
            } else if (FrmPrincipal.listadoDeVacas.get(i).getEstado().equals("Enferma")) {
                this.contVacasEnfermas++;
            }

        }
        this.contVacasTotal = this.contVacasSanas + this.contVacasEnfermas;
    }

    private void cargarInfoEnlbl() {
        this.lblVacasTotal.setText(Integer.toString(this.contVacasTotal));
        this.lblVacasSanas.setText(Integer.toString(this.contVacasSanas));
        this.lblVacasEnfermas.setText(Integer.toString(this.contVacasEnfermas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIconCasa = new javax.swing.JLabel();
        btnVerFacturas = new javax.swing.JButton();
        btnKilaje = new javax.swing.JButton();
        btnAnadirVaca = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNombrePropietario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVacasTotal = new javax.swing.JLabel();
        lblVacasSanas = new javax.swing.JLabel();
        lblVacasEnfermas = new javax.swing.JLabel();
        btnVacasTotal = new javax.swing.JButton();
        btnVacasEnfermas = new javax.swing.JButton();
        btnVacasSanas = new javax.swing.JButton();
        imgVaca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        lblIconCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_hombre_azul.png"))); // NOI18N

        btnVerFacturas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVerFacturas.setText("Ver facturas");

        btnKilaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKilaje.setText("Ver kilaje");

        btnAnadirVaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnadirVaca.setText("Añadir vaca");
        btnAnadirVaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirVacaActionPerformed(evt);
            }
        });

        btnVender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVender.setText("Vender");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerFacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(btnKilaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirVaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconCasa)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIconCasa)
                .addGap(30, 30, 30)
                .addComponent(btnVerFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKilaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnadirVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Panel de información Propietario");

        lblNombrePropietario.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lblNombrePropietario.setForeground(new java.awt.Color(0, 204, 204));
        lblNombrePropietario.setText(".");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Numero de vacas en total: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Numero de vacas sanas: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Numero de vacas enfermas: ");

        lblVacasTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblVacasTotal.setText(".");

        lblVacasSanas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblVacasSanas.setText(".");

        lblVacasEnfermas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblVacasEnfermas.setText(".");

        btnVacasTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesBotones/ver.png"))); // NOI18N
        btnVacasTotal.setText("Ver");
        btnVacasTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacasTotalActionPerformed(evt);
            }
        });

        btnVacasEnfermas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesBotones/ver.png"))); // NOI18N
        btnVacasEnfermas.setText("Ver");
        btnVacasEnfermas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacasEnfermasActionPerformed(evt);
            }
        });

        btnVacasSanas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesBotones/ver.png"))); // NOI18N
        btnVacasSanas.setText("Ver");
        btnVacasSanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacasSanasActionPerformed(evt);
            }
        });

        imgVaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vaca4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblNombrePropietario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgVaca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(43, 43, 43)
                                        .addComponent(lblVacasEnfermas, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblVacasSanas, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                            .addComponent(lblVacasTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnVacasSanas)
                                        .addComponent(btnVacasTotal))
                                    .addComponent(btnVacasEnfermas, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNombrePropietario)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblVacasTotal)
                    .addComponent(btnVacasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblVacasSanas)
                    .addComponent(btnVacasSanas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVacasEnfermas)
                        .addComponent(btnVacasEnfermas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgVaca)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVacasTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacasTotalActionPerformed
        FrmDialogTablaVacas frmDialogTablaVacas = new FrmDialogTablaVacas(null, true, 1);
        frmDialogTablaVacas.setVisible(true);
        //Al cerrar se vuelve a cargar la info por si hay actualizaciones
        informacionConteoDeVacas();
        cargarInfoEnlbl();
    }//GEN-LAST:event_btnVacasTotalActionPerformed

    private void btnVacasSanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacasSanasActionPerformed
        FrmDialogTablaVacas frmDialogTablaVacas = new FrmDialogTablaVacas(null, true, 2);
        frmDialogTablaVacas.setVisible(true);
        //Al cerrar se vuelve a cargar la info por si hay actualizaciones
        informacionConteoDeVacas();
        cargarInfoEnlbl();
    }//GEN-LAST:event_btnVacasSanasActionPerformed

    private void btnVacasEnfermasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacasEnfermasActionPerformed
        FrmDialogTablaVacas frmDialogTablaVacas = new FrmDialogTablaVacas(null, true, 3);
        frmDialogTablaVacas.setVisible(true);
        //Al cerrar se vuelve a cargar la info por si hay actualizaciones
        informacionConteoDeVacas();
        cargarInfoEnlbl();
    }//GEN-LAST:event_btnVacasEnfermasActionPerformed

    private void btnAnadirVacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirVacaActionPerformed
        FrmDiagTipoDeIngreso frmDiagTipoDeIngreso = new FrmDiagTipoDeIngreso(null, true);
        frmDiagTipoDeIngreso.setVisible(true);
        //Al cerrar se vuelve a cargar la info por si hay actualizaciones
        informacionConteoDeVacas();
        cargarInfoEnlbl();
    }//GEN-LAST:event_btnAnadirVacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiagPanelPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiagPanelPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiagPanelPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiagPanelPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDiagPanelPropietario dialog = new FrmDiagPanelPropietario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirVaca;
    private javax.swing.JButton btnKilaje;
    private javax.swing.JButton btnVacasEnfermas;
    private javax.swing.JButton btnVacasSanas;
    private javax.swing.JButton btnVacasTotal;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVerFacturas;
    private javax.swing.JLabel imgVaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIconCasa;
    private javax.swing.JLabel lblNombrePropietario;
    private javax.swing.JLabel lblVacasEnfermas;
    private javax.swing.JLabel lblVacasSanas;
    private javax.swing.JLabel lblVacasTotal;
    // End of variables declaration//GEN-END:variables

}
